apiVersion: v1
kind: Service
metadata:
  name: food-service
  namespace: ns-github-actions-test  # 네임스페이스 지정
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # NLB를 사용
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # External 로드밸런서로 설정
spec:
  selector:
    app: food-app  # Deployment와 연결된 Pod을 선택
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # 외부에서 접근할 수 있도록 설정

