name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker 이미지 빌드 및 푸시
    - name: Log in to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_USERNAME/github-action-test:latest .
        docker push $DOCKER_USERNAME/github-action-test:latest

    # 3. kubectl 설정
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0'

    # 4. EKS에 배포
    - name: Deploy to EKS
      run: |
        echo "$EKS_KUBECONFIG" > kubeconfig
        export KUBECONFIG=kubeconfig
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml

